name: Install & Test Package with MLflow

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

jobs:
  build-job:
    name: Build (Linux)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: fsds
          environment-file: deploy/conda/fsds-env.yml
          python-version: 3.11
          auto-update-conda: true

      - name: Install tree CLI tool
        run: |
          sudo apt-get update
          sudo apt install -y tree

      - name: Show directory tree before build
        run: tree -L 3

      - name: Build the package
        run: |
          conda activate fsds
          python -m build

      - name: Show directory tree after build
        run: tree -L 3

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

      - name: Upload environment file
        uses: actions/upload-artifact@v4
        with:
          name: conda-env-file
          path: deploy/conda/fsds-env.yml

  install-job:
    name: Install (Linux)
    runs-on: ubuntu-latest
    needs: build-job
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist/

      - name: Download environment file
        uses: actions/download-artifact@v4
        with:
          name: conda-env-file
          path: deploy/conda/

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: fsds
          environment-file: deploy/conda/fsds-env.yml
          python-version: 3.11
          auto-update-conda: true

      - name: Install MLflow
        run: |
          conda activate fsds
          pip install mlflow

      - name: Install package
        run: |
          conda activate fsds
          pip install dist/*.whl

      - name: Create required directories
        run: |
          mkdir -p datasets/housing
          mkdir -p models
          mkdir -p models/metrics
          touch models/best_model.pkl

      - name: Run workflow script ingest data
        run: |
          conda activate fsds
          python scripts/ingest_data.py

      - name: Run workflow script train (with MLflow tracking)
        run: |
          conda activate fsds
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI"
          python scripts/train.py

      - name: Run workflow script score
        run: |
          conda activate fsds
          python scripts/score.py
